name: discord-meeting-reminder

on:
  schedule:
    - cron: '* * * * *' 

jobs:
  send-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: send discord message
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
          -d '{"content": "🔔 Reminder: Dev meeting starting soon!"}' \
          $DISCORD_WEBHOOK
