name: discord-meeting-reminder

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'    # runs every 5 minutes

jobs:
  send-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: send discord message
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
          -d '{"content": "🔔 testing every 5min!"}' \
          $DISCORD_WEBHOOK
