name: discord-meeting-reminder

on:
  schedule:
    # runs every wednesday at 5pm, 8pm, and 8:55pm EST
    - cron: '0 21 * * 3'    # 5pm EST (21:00 UTC)
    - cron: '0 0 * * 4'     # 8pm EST (00:00 UTC next day)
    - cron: '55 0 * * 4'    # 8:55pm EST (00:55 UTC next day)

jobs:
  send-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: send discord message
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
          -d '{"content": "🔔 Reminder: Dev meeting starting soon!"}' \
          $DISCORD_WEBHOOK
